export const GET_APPOINTMENTS_FETCHING = "GET_APPOINTMENTS_FETCHING";
export const GET_APPOINTMENTS_FULFILLED = "GET_APPOINTMENTS_FULFILLED";
export const GET_APPOINTMENTS_REJECTED = "GET_APPOINTMENTS_REJECTED";

export const ADD_APPOINTMENT_FETCHING = "ADD_APPOINTMENT_FETCHING";
export const ADD_APPOINTMENT_FULFILLED = "ADD_APPOINTMENT_FULFILLED";
export const ADD_APPOINTMENT_REJECTED = "ADD_APPOINTMENT_REJECTED";

export const EDIT_APPOINTMENT_FETCHING = "EDIT_APPOINTMENT_FETCHING";
export const EDIT_APPOINTMENT_FULFILLED = "EDIT_APPOINTMENT_FULFILLED";
export const EDIT_APPOINTMENT_REJECTED = "EDIT_APPOINTMENT_REJECTED";

export const DELETE_APPOINTMENT_FETCHING = "DELETE_APPOINTMENT_FETCHING";
export const DELETE_APPOINTMENT_FULFILLED = "DELETE_APPOINTMENT_FULFILLED";
export const DELETE_APPOINTMENT_REJECTED = "DELETE_APPOINTMENT_REJECTED";
