export const GET_BOILERS_PENDING = "GET_BOILERS_PENDING";
export const GET_BOILERS_FULFILLED = "GET_BOILERS_FULFILLED";
export const GET_BOILERS_REJECTED = "GET_BOILERS_REJECTED";

export const POST_BOILERS_PENDING = "POST_BOILERS_PENDING";
export const POST_BOILERS_FULFILLED = "POST_BOILERS_FULFILLED";
export const POST_BOILERS_REJECTED = "POST_BOILERS_REJECTED";

export const PUT_BOILERS_PENDING = "PUT_BUILDING_PENDING";
export const PUT_BOILERS_FULFILLED = "PUT_BUILDING_FULFILLED";
export const PUT_BOILERS_REJECTED = "PUT_BUILDING_REJECTED";

export const DELETE_BOILERS_PENDING = "DELETE_BOILERS_PENDING";
export const DELETE_BOILERS_FULFILLED = "DELETE_BOILERS_FULFILLED";
export const DELETE_BOILERS_REJECTED = "DELETE_BOILERS_REJECTED";
