export const GET_BOILERTYPES_FETCHING = "SHOW_BOILERTYPES_FETCHING";
export const GET_BOILERTYPES_FULFILLED = "SHOW_BOILERTYPES_FULFILLED";
export const GET_BOILERTYPES_REJECTED = "SHOW_BOILERTYPES_REJECTED";

export const ADD_BOILERTYPES_FETCHING = "ADD_BOILERTYPES_FETCHING";
export const ADD_BOILERTYPES_FULFILLED = "ADD_BOILERTYPES_FULFILLED";
export const ADD_BOILERTYPES_REJECTED = "ADD_BOILERTYPES_REJECTED";

export const EDIT_BOILERTYPES_FETCHING = "EDIT_BOILERTYPES_FETCHING";
export const EDIT_BOILERTYPES_FULFILLED = "EDIT_BOILERTYPES_FULFILLED";
export const EDIT_BOILERTYPES_REJECTED = "EDIT_BOILERTYPES_REJECTED";

export const DELETE_BOILERTYPES_FETCHING = "DELETE_BOILERTYPES_FETCHING";
export const DELETE_BOILERTYPES_FULFILLED = "DELETE_BOILERTYPES_FULFILLED";
export const DELETE_BOILERTYPES_REJECTED = "DELETE_BOILERTYPES_REJECTED";
