export const GET_CUSTOMERS_FETCHING = "GET_CUSTOMERS_FETCHING";
export const GET_CUSTOMERS_FULFILLED = "GET_CUSTOMERS_FULFILLED";
export const GET_CUSTOMERS_REJECTED = "GET_CUSTOMERS_REJECTED";

export const POST_CUSTOMER_FETCHING = "POST_CUSTOMER_FETCHING";
export const POST_CUSTOMER_FULFILLED = "POST_CUSTOMER_FULFILLED";
export const POST_CUSTOMER_REJECTED = "POST_CUSTOMER_REJECTED";

export const PUT_CUSTOMER_FETCHING = "PUT_CUSTOMER_FETCHING";
export const PUT_CUSTOMER_FULFILLED = "PUT_CUSTOMER_FULFILLED";
export const PUT_CUSTOMER_REJECTED = "PUT_CUSTOMER_REJECTED";

export const DELETE_CUSTOMER_FETCHING = "DELETE_CUSTOMER_FETCHING";
export const DELETE_CUSTOMER_FULFILLED = "DELETE_CUSTOMER_FULFILLED";
export const DELETE_CUSTOMER_REJECTED = "DELETE_CUSTOMER_REJECTED";
